### ISSUE TITLE
Resource page - more button needs two click to expand

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#279] opened 2017-10-02 15:59 UTC
### Done criteria
- [x] Ensure 'More' button on resource page only needs one click to expand

---
### ALNAP to check
- [x] More button works as expected

**Comment by angievanhegan** [comment] 2017-10-02 15:59
@russ-manta A new bug to size. I'm waiting on Tim to confirm the browser he's using. Thanks

**Comment by meldera** [comment] 2017-10-09 10:10
Would be useful to know, as I was not able to reproduce this...

**Comment by russ-manta** [comment] 2017-10-09 14:52
@arseni timharcourtpowell [< 1 minute ago] 
Just tried it again - the one on the homepage seems to work on first click, but the panels one is still two clicks on this page: http://alnap-dev.mrmdev.co.uk/events/annual-meetings/31st-annual-meeting-changing-humanitarian-action

**Comment by russ-manta** [comment] 2017-10-10 08:46
@meldera just tested - still needs two clicks from me

**Comment by meldera** [comment] 2017-10-10 08:56
Some JS changes were overwritten since yesterday. Now fixed again...

**Comment by Maria-alnap** [comment] 2017-10-10 14:40
This is ok now. Will move to done.

**Closed** 2017-10-20 15:26 UTC
Labels: Bug
