### ISSUE TITLE
(#210) Scope/Wireframe annual meeting page

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#65] opened 2017-06-05 20:06 UTC
Linked to #6 (Theme annual meetings landing page) and #35 (Build Annual meetings landing page)

-----
### Before the meeting:
- [ ] Description
- [ ] Concept note
- [ ] Calls for proposals, cost and registration info.
- [ ] Programme
- [ ] Background paper,

### After the meeting:
- [ ] audio of the panel discussions
- [ ] YouTube playlist (opening panel, keynote speech, ted talk style presentations)
- [ ] links to reports released or featured at the event
- [ ] Storify
- [ ] Twitter feed

### See examples:  
www.alnap.org/31am
www.alnap.org/what-we-do/effectiveness/meeting-2015 

----

**Comment by angievanhegan** [comment] 2017-06-06 16:14
Annual meetings require a substantial post-event page (eg. http://www.alnap.org/what-we-do/effectiveness/meeting-2015).  How will we deal with this?  A separate content type?

**Comment by angievanhegan** [comment] 2017-06-06 16:44
@ican-icant Can we take this into account when we do the event coverage page, or do you think they need to be different?

**Comment by ican-icant** [comment] 2017-06-12 10:25
@dave-manta @angievanhegan  @nadia847  The only difference I can see between a normal event coverage page and the annual meeting is the addition of sessions / timetable. Maybe we could just add this to the coverage content type?

**Comment by dave-manta** [comment] 2017-06-12 13:10
@ican-icant Can it be achieved with nuggets?

**Comment by angievanhegan** [comment] 2017-06-12 13:18
@Maria-alnap @ican-icant 
Copied from Slack

SL: We need to know what you'd like to add to the coverage after an annual event and how it might differ from a normal event that is covered.

MG: What we do is that we create a basic content page (the only ones we have at the moment, tbh) and pre meeting we put a description, concept note, calls for proposals, cost and registration info. As the meeting comes closer in time, we release other material there, such as the programme, background paper, etc. After the meeting, we also add new content from the meeting itself, mainly in AV form (audio of the panel discussions and clips for the opening panel, keynote speech, ted talk style presentations) the link to the most recent meeting is www.alnap.org/31am

regarding what we would add to a basic event coverage, I'd say at least a write up, a youtube playlist/clip of the discussion and links to the report that was released/featured in the event+ links to any related bite sized material around it. Sometimes we would add a storify and/or twitter feed as well

**Comment by dave-manta** [comment] 2017-06-12 13:29
@angievanhegan I think this task needs renaming or the text about coverage moved elsewhere as it's current title relates to the landing page that lists all annual meetings, not the individual meeting pages.

**Comment by angievanhegan** [comment] 2017-06-14 17:18
@dave-manta I've updated the title so that it's now about a specific annual meeting page.

**Comment by angievanhegan** [comment] 2017-06-14 17:29
@dave-manta @russ-manta @nadia847 Who can tell me if we can display a session timetable with nuggets? See here for an example www.alnap.org/31am Thanks

**Comment by nadia847** [comment] 2017-06-15 08:49
@angievanhegan @dave-manta yes, we can add tables in Content block nuggets which, unless we need something really templated, eg drugs on smo, should suffice.

**Comment by angievanhegan** [comment] 2017-06-15 18:06
So, this doesn't look like it's going to need a wireframe. Great.

**Comment by angievanhegan** [comment] 2017-08-03 16:04
This can all be done in a normal event page. Therefore this is a DUPE of #30

**Comment by angievanhegan** [comment] 2017-08-03 16:09
Done

**Closed by angievanhegan** 2017-08-03 16:09 UTC
Labels: Events, Needs scoping, Wireframe
