### ISSUE TITLE
Decide how we are using user profiles

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#145] opened 2017-06-15 16:03 UTC
- [ ] Decide how we're using user profiles
- [ ] Create issues in waffle as a result of this decision
- [ ] Make sure we have the appropriate work packages on the Roadmap
- [ ] Make sure we have an issue for using this design: https://invis.io/6GC6FJ72N

**Comment by nadia847** [comment] 2017-06-16 10:50
@angievanhegan @russ-manta Is this kinda a duplicate of #45?

**Closed** 2017-06-23 13:55 UTC
Labels: Done, Users
