### ISSUE TITLE
(#208) Build & theme organisation content type and views

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#44] opened 2017-06-05 15:05 UTC
### Dependencies
- [x] Can't be done until questions #66 resolved (Member CT vs Agency CT vs Civi data) 
---
### Done criteria
Views to display on the node:
- [x] Events (upcoming. Should there be access to past events?) 
- [x] Resources - they have uploaded and ones ALNAP tag for them 
- [x] Blogs & News
- [ ] Webinars (update: these are events that are added as a resource and then shown in the resources view)
- [ ] Jobs (not required on page anymore)
- [x] Logo for organisation
- [ ] Relationships to other content types eg events, resources, news, blogs etc
- [x] Theme node and views shown on node
---
### Designs
- [Member organisation page](https://invis.io/N4CLJYB26)
---
### ALNAP to check
[Sample member]( http://alnap-dev.mrmdev.co.uk/test-organisationmember)
- [ ] Page looks like design

**Comment by melkers** [comment] 2017-06-05 15:28
Blocked until questions answered

**Comment by angievanhegan** [comment] 2017-06-05 16:04
@melkers Can you specify which questions and who's answering them please? This needs to be assigned to someone. Thanks

**Comment by angievanhegan** [comment] 2017-06-06 16:53
I need to clarify what constituency was. It came up at the client meeting on 6/6

**Comment by dave-manta** [comment] 2017-06-06 19:11
@angievanhegan you can see the consituency list (which is essentially type of org) here: http://www.alnap.org/members/full-associate.

This data will be in CiviCRM and Russ and I are in discussion about how to deal with that on #66

**Comment by dave-manta** [comment] 2017-06-08 13:10
@angievanhegan Panel list... not sure we can do this one, except maybe putting it in the body.

**Comment by angievanhegan** [comment] 2017-06-08 13:24
@dave-manta Do we have enough design patterns already to put the panelist in the body?

**Comment by dave-manta** [comment] 2017-06-08 14:05
@angievanhegan I'm afraid I'm not close to design patterns or what they want to show with panel lists.  This data may be housed in Civi, but it won't be exposed to Drupal and providing anything more than an ability for them to edit the body of text for an org, I would say is outside of scope.

**Comment by angievanhegan** [comment] 2017-06-08 14:15
@dave-manta Would you like me to just confirm that with the client, or can we just go ahead with it?

**Comment by dave-manta** [comment] 2017-06-08 14:21
@angievanhegan probably worth telling them that will have to put panel info in a wysiwyg and that we're not doing anything 'clever'.

**Comment by angievanhegan** [comment] 2017-06-09 13:37
Maria is fine with doing this in text.

**Comment by dilwarhussain** [comment] 2017-06-14 13:42
@dave-manta @angievanhegan A few questions:
1. Upcoming events? Access to past events? Any decision on this?
2. What's the difference between resources they have uploaded and ones ALNAP tag for them? They will both be linked via the entity reference, no?
3. Webinars are a type of resource and will be included in the view of resources?
4. What is a panel list? If it's being shown in the body, then we will need a main content section.

**Comment by dave-manta** [comment] 2017-06-14 14:05
@dilwarhussain 

1. I think access to past events should just be a filter on the search, but perhaps @ican-icant should feed in.  Not sure what the issue is with upcoming.
2.  I think this is part of a wider discussion which I was having with Russ yesterday on #66 and I would check in with @russ-manta on this.
3. That's a good question.  I think the upcoming webinar is an event, but when complete the recorded webinar is uploaded as a resource.  We could check this with Maria or perhaps you might be able to work it out by looking at the current site.  If that is the case, hopefully the way we're building the site can handle this and we would just link from the past event to the resource, ya?
4. I believe the panel list is content for the member node and it just lists the events where they have been on a panel.

There's perhaps still debate (with Russ) on whether we have an organisation content type, as we might not even have one, however you may no more from Russ, than from me.

**Comment by russ-manta** [comment] 2017-06-14 14:14
@dave-manta @dilwarhussain we've gone with an organisation content type for now and I think we will always have one it just how integrated with Civi it's going to be. I'm trying to test that part now

**Comment by dave-manta** [comment] 2017-06-14 14:23
OK @russ-manta. I think it's really important that your thoughts so far are documented here #66 as that would have made some of my responses to Dilwar, easier.

**Comment by russ-manta** [comment] 2017-06-14 14:32
@dave re panel list you mention member content type. I assume you mean member as in person and not organisation?

**Comment by dave-manta** [comment] 2017-06-14 14:34
@russ-manta sorry, meant organisation.

**Comment by dave-manta** [comment] 2017-06-14 14:35
@russ-manta there's been a separate discussion about panel list somewhere...

**Comment by russ-manta** [comment] 2017-07-31 15:46
@ican-icant for organisations, presumably we should be displaying address, website and description much like on the current site: http://www.alnap.org/members/134.aspx  vs http://alnap-dev.mrmdev.co.uk/actions-against-hunger  we only have a wireframe at the moment - do we need a design?

**Comment by ican-icant** [comment] 2017-08-03 14:26
@russ-manta no design necessary - just use the wireframe? There will be no news as far as I'm aware tho.

**Comment by russ-manta** [comment] 2017-08-04 13:33
@dilwarhussain can you complete the build/theme of the organisation node based on the wireframe: https://projects.invisionapp.com/d/main#/console/10292473/222960812/preview and http://alnap-dev.mrmdev.co.uk/alnap-0

**Comment by dilwarhussain** [comment] 2017-08-08 13:20
@nadia847 http://alnap-dev.mrmdev.co.uk/test-organisationmember

**Comment by Maria-alnap** [comment] 2017-08-09 10:46
@angievanhegan Not sure this is ready for sign off yet? I can only see the logo of the organisation on the page... nothing else

**Comment by angievanhegan** [comment] 2017-08-09 13:49
@Maria-alnap Sorry, try now with the new link - this page has some actual information on!

**Comment by Maria-alnap** [comment] 2017-08-14 14:22
@ican-icant This looks ok. I'll sign off and move to done

**Closed** 2017-09-14 13:52 UTC
Labels: Build, Members
