### ISSUE TITLE
(#210) Build events node views

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#162] opened 2017-06-20 13:25 UTC
### Done criteria
- [ ] RHS content on node and anything else requiring views
- [ ] ?
- [ ] ?
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment] 2017-07-17 15:59
This is a dupe of #30

**Closed by angievanhegan** 2017-07-17 15:59 UTC
Labels: Build, Events, Needs DONE criteria, Review
